apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80  # Porta do Pod que o Service deve encaminhar
    nodePort: 30001  # Porta NodePort específica
  selector:
    app: sistema-noticias  # Este deve corresponder à label do Pod que você deseja expor
