apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80  # Porta do Pod que o Service deve encaminhar
    nodePort: 30000  # Porta NodePort específica
  selector:
    app: portal-noticias  # Este deve corresponder à label do Pod que você deseja expor
